version: "3"
services:
 rabbitmq:
  image: "rabbitmq:3-management"
  ports:
    - "5672:5672" # AMQP 0-9-1 Messaging Protokol pro universalni ucel
    - "15672:15672" # web manager
  volumes:
    - "rabbitmq_data:/data"
volumes:
  rabbitmq_data: